const ActionTypes = {
  LIST_FILES: 'LIST_FILES',
  ADD_FOLDER_LIST: "ADD_FOLDER_LIST",
  GET_FOLDERS: 'GET_FOLDERS',
  REFRESH_FOLDER: 'REFRESH_FOLDER',
  ADD_FOLDERS: "ADD_FOLDERS",
  ADD_FILES: "ADD_FILES",
  REMOVE_FILES: "REMOVE_FILES",
};

export default ActionTypes;
